name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - name: Lint Terraform code
        run: |
          terraform fmt -recursive -check
      - name: Validate Terraform example
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: examples/basic
